# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import command_pb2 as command__pb2


class CommanderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LogIn = channel.unary_unary(
        '/Commander/LogIn',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Success.FromString,
        )
    self.GetStaticInfo = channel.unary_unary(
        '/Commander/GetStaticInfo',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.StaticInfo.FromString,
        )
    self.GetFastIntervalInfo = channel.unary_unary(
        '/Commander/GetFastIntervalInfo',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.FastIntervalInfo.FromString,
        )
    self.GetSlowIntervalInfo = channel.unary_unary(
        '/Commander/GetSlowIntervalInfo',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.SlowIntervalInfo.FromString,
        )
    self.GetShortInfo = channel.unary_unary(
        '/Commander/GetShortInfo',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.Welcome.FromString,
        )
    self.GetDiskInfo = channel.unary_unary(
        '/Commander/GetDiskInfo',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.DiskInfo.FromString,
        )
    self.SetVolume = channel.unary_unary(
        '/Commander/SetVolume',
        request_serializer=command__pb2.Success.SerializeToString,
        response_deserializer=command__pb2.Success.FromString,
        )
    self.SetBrightness = channel.unary_unary(
        '/Commander/SetBrightness',
        request_serializer=command__pb2.Level.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.Shutdown = channel.unary_unary(
        '/Commander/Shutdown',
        request_serializer=command__pb2.ShutdownParams.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.GetElementsInPath = channel.unary_unary(
        '/Commander/GetElementsInPath',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Elements.FromString,
        )
    self.OpenFile = channel.unary_unary(
        '/Commander/OpenFile',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.File.FromString,
        )
    self.DeleteFile = channel.unary_unary(
        '/Commander/DeleteFile',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.CreateNewFolder = channel.unary_unary(
        '/Commander/CreateNewFolder',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.SetBackground = channel.unary_unary(
        '/Commander/SetBackground',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.OpenCDROM = channel.unary_unary(
        '/Commander/OpenCDROM',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.OpenInternetBrowser = channel.unary_unary(
        '/Commander/OpenInternetBrowser',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.Screenshot = channel.unary_unary(
        '/Commander/Screenshot',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.File.FromString,
        )
    self.GetKeyLogs = channel.unary_unary(
        '/Commander/GetKeyLogs',
        request_serializer=command__pb2.Empty.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.OpenInfoWindow = channel.unary_unary(
        '/Commander/OpenInfoWindow',
        request_serializer=command__pb2.Alert.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.Say = channel.unary_unary(
        '/Commander/Say',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )
    self.Click = channel.unary_unary(
        '/Commander/Click',
        request_serializer=command__pb2.Command.SerializeToString,
        response_deserializer=command__pb2.Command.FromString,
        )


class CommanderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LogIn(self, request, context):
    """Auth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStaticInfo(self, request, context):
    """Info
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFastIntervalInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSlowIntervalInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetShortInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiskInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetVolume(self, request, context):
    """Regulation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBrightness(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Shutdown(self, request, context):
    """ON OFF
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetElementsInPath(self, request, context):
    """File manager
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNewFolder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBackground(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenCDROM(self, request, context):
    """Additional
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenInternetBrowser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Screenshot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKeyLogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenInfoWindow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Say(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Click(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommanderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LogIn': grpc.unary_unary_rpc_method_handler(
          servicer.LogIn,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Success.SerializeToString,
      ),
      'GetStaticInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetStaticInfo,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.StaticInfo.SerializeToString,
      ),
      'GetFastIntervalInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetFastIntervalInfo,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.FastIntervalInfo.SerializeToString,
      ),
      'GetSlowIntervalInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetSlowIntervalInfo,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.SlowIntervalInfo.SerializeToString,
      ),
      'GetShortInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetShortInfo,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.Welcome.SerializeToString,
      ),
      'GetDiskInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDiskInfo,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.DiskInfo.SerializeToString,
      ),
      'SetVolume': grpc.unary_unary_rpc_method_handler(
          servicer.SetVolume,
          request_deserializer=command__pb2.Success.FromString,
          response_serializer=command__pb2.Success.SerializeToString,
      ),
      'SetBrightness': grpc.unary_unary_rpc_method_handler(
          servicer.SetBrightness,
          request_deserializer=command__pb2.Level.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'Shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.Shutdown,
          request_deserializer=command__pb2.ShutdownParams.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'GetElementsInPath': grpc.unary_unary_rpc_method_handler(
          servicer.GetElementsInPath,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Elements.SerializeToString,
      ),
      'OpenFile': grpc.unary_unary_rpc_method_handler(
          servicer.OpenFile,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.File.SerializeToString,
      ),
      'DeleteFile': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteFile,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'CreateNewFolder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNewFolder,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'SetBackground': grpc.unary_unary_rpc_method_handler(
          servicer.SetBackground,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'OpenCDROM': grpc.unary_unary_rpc_method_handler(
          servicer.OpenCDROM,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'OpenInternetBrowser': grpc.unary_unary_rpc_method_handler(
          servicer.OpenInternetBrowser,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'Screenshot': grpc.unary_unary_rpc_method_handler(
          servicer.Screenshot,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.File.SerializeToString,
      ),
      'GetKeyLogs': grpc.unary_unary_rpc_method_handler(
          servicer.GetKeyLogs,
          request_deserializer=command__pb2.Empty.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'OpenInfoWindow': grpc.unary_unary_rpc_method_handler(
          servicer.OpenInfoWindow,
          request_deserializer=command__pb2.Alert.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'Say': grpc.unary_unary_rpc_method_handler(
          servicer.Say,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
      'Click': grpc.unary_unary_rpc_method_handler(
          servicer.Click,
          request_deserializer=command__pb2.Command.FromString,
          response_serializer=command__pb2.Command.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Commander', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
